_name_or_path:
    value: Qwen/Qwen3-VL-4B-Instruct
_wandb:
    value:
        cli_version: 0.28.1
        e:
            rrsj8jn0ogjuaj8knc690diccdi1a0in:
                args:
                    - --task_name
                    - mol_rep_ocr
                    - --model_name
                    - qwen3_vl_4b_i
                    - --training_method
                    - sft_lora
                codePath: scripts/sft.py
                codePathLocal: scripts/sft.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16534913024"
                email: kendeng0418@gmail.com
                executable: /root/miniconda3/envs/vllm/bin/python3.12
                gpu: NVIDIA GeForce RTX 4090 D
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-21e30c63-afea-89f1-dda3-7ce6abc35bbd
                host: autodl-container-b7b443bad6-fa3e0be6
                memory:
                    total: "1081834991616"
                os: Linux-5.15.0-94-generic-x86_64-with-glibc2.35
                program: /root/mol-llm/scripts/sft.py
                python: CPython 3.12.13
                root: /root/mol-llm
                startedAt: "2026-08-13T10:16:37.093932Z"
                writerId: rrsj8jn0ogjuaj8knc690diccdi1a0in
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.12.13
            "5": 0.28.1
            "6": 5.14.1
            "9":
                "1": transformers_trainer
            "12": 0.28.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_offloading:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen3VLForConditionalGeneration
assistant_only_loss:
    value: false
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chat_template_path:
    value: null
chunk_size_feed_forward:
    value: 0
completion_only_loss:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_kwargs:
    value: null
dataset_num_proc:
    value: null
dataset_text_field:
    value: text
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token:
    value: <EOS_TOKEN>
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_packing:
    value: null
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: null
fsdp_config:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 16
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: false
greater_is_better:
    value: null
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
image_token_id:
    value: 151655
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0001
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 16
logging_strategy:
    value: steps
loss_type:
    value: chunked_nll
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 8000
max_steps:
    value: -1
metric_for_best_model:
    value: null
model/num_parameters:
    value: 4470845952
model_init_kwargs:
    value: null
model_type:
    value: qwen3_vl
neftune_noise_alpha:
    value: null
num_train_epochs:
    value: 5
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ckpt/ocr/qwen3_vl_4b_i_sft_lora_ocr/v1/20260813_181545/
output_hidden_states:
    value: false
packing:
    value: false
packing_strategy:
    value: bfd
pad_to_multiple_of:
    value: null
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 151643
padding_free:
    value: false
parallelism_config:
    value: null
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            lora_ga_config: null
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            monteclora_config: null
            peft_type: LORA
            peft_version: 0.20.0
            qalora_group_size: 16
            r: 16
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - gate_proj
                - up_proj
                - k_proj
                - o_proj
                - v_proj
                - q_proj
                - down_proj
            target_parameters: null
            task_type: null
            trainable_token_indices: null
            use_bdlora: null
            use_dora: false
            use_qalora: false
            use_rslora: false
            velora_config: null
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 1
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
router_aux_loss_coef:
    value: 0.001
run_name:
    value: qwen3_vl_4b_i_sft_lora_ocr_v1_20260813_181545
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: null
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
shuffle_dataset:
    value: false
skip_memory_metrics:
    value: true
text_config:
    value:
        _name_or_path: ""
        architectures: null
        attention_bias: false
        attention_dropout: 0
        bos_token_id: 151643
        chunk_size_feed_forward: 0
        dtype: float32
        eos_token_id: 151645
        head_dim: 128
        hidden_act: silu
        hidden_size: 2560
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        initializer_range: 0.02
        intermediate_size: 9728
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        max_position_embeddings: 262144
        model_type: qwen3_vl_text
        num_attention_heads: 32
        num_hidden_layers: 36
        num_key_value_heads: 8
        output_attentions: false
        output_hidden_states: false
        pad_token_id: null
        problem_type: null
        return_dict: true
        rms_norm_eps: 1e-06
        rope_parameters:
            mrope_interleaved: true
            mrope_section:
                - 24
                - 20
                - 20
            rope_theta: 5000000
            rope_type: default
        tie_word_embeddings: true
        use_cache: true
        vocab_size: 151936
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.14.1
truncation_mode:
    value: keep_start
trust_remote_code:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
video_token_id:
    value: 151656
vision_config:
    value:
        _name_or_path: ""
        architectures: null
        chunk_size_feed_forward: 0
        deepstack_visual_indexes:
            - 5
            - 11
            - 17
        depth: 24
        dtype: float32
        hidden_act: gelu_pytorch_tanh
        hidden_size: 1024
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        in_channels: 3
        initializer_range: 0.02
        intermediate_size: 4096
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        model_type: qwen3_vl_vision
        num_heads: 16
        num_position_embeddings: 2304
        out_hidden_size: 2560
        output_attentions: false
        output_hidden_states: false
        patch_size: 16
        problem_type: null
        return_dict: true
        spatial_merge_size: 2
        temporal_patch_size: 2
vision_end_token_id:
    value: 151653
vision_start_token_id:
    value: 151652
warmup_ratio:
    value: null
warmup_steps:
    value: 0.03
weight_decay:
    value: 0
